// import scream from "./img/scream.jpg";
// import TheBatman from "./img/TheBatman.jpg";
// import TheLostCity from "./img/TheLostCity.jpg";
// import TheNorthman from "./img/TheNorthman.jpg";
export const list = [
  { id:Math.random(),
    title: "scream",
    description: "first movie",
    imgsrc:"https://i.egycdn.com/pic/WmFwZndlY212bVR2bWJtbW1ibWVjY05tdk52bXhqbW1L.jpg",
    rating: 50,
    trailer:"https://www.youtube.com/embed/beToTslH17s",
    done: "true",
  },
  {id:Math.random(),
    title: "The Batman",
    description: "second movie",
    imgsrc: "https://i.egycdn.com/pic/WmFwZndlY212bXBZWXZtRW12RWNjdHdsbXZtTE56UA.jpg",
    rating: 60,
    trailer:"https://www.youtube.com/embed/mqqft2x_Aa4",
    done: "true",
  },
  {id:Math.random(),
    title: "Th Lost City",
    description: "third movie",
    imgsrc: "https://i.egycdn.com/pic/RHNhSUNlY212bVl2bWptWXZtYWNtSWx2Y0tQdk5qbWc.jpg",
    rating: 30,
    trailer:"https://www.youtube.com/embed/nfKO9rYDmE8",
    done: "true",
  },
  {id:Math.random(),
    title: "The Northman",
    description: "fourth movie",
    imgsrc: "https://i.egycdn.com/pic/RHNhSUNlY212bW12Y3ZObXZjdmNFY3hQbUxrdHdQbWc.jpg",
    rating: 70,
    trailer:"https://www.youtube.com/embed/oMSdFM12hOw",
    done: "true",
  },
];
